Mychem: LibHandler Class Reference
LibHandler Class Reference
#include <dlhandler.h>
Public Member Functions
LibHandler ()
~LibHandler ()
bool isLoaded ()
Constructor & Destructor Documentation
LibHandler ()
References OBLIBRARY.
~LibHandler ()
Member Function Documentation
bool isLoaded ()
Referenced by CMLconversion(), conversion(), conversionCAN(), conversionCML(), conversionFPT(), conversionV3000(), getAcceptors(), getAtomCount(), getBondCount(), getDonors(), getExactMass(), getFormula(), getHeavyAtomCount(), getLogP(), getMolWeight(), getMR(), getPSA(), getRingCount(), getRotableBondCount(), getTotalCharge(), is2D(), is3D(), isChiral(), match_substructure(), ob_add_hydrogens(), ob_remove_hydrogens(), ob_strip_salts(), serializeMolecule(), substructure_atom_ids(), substructure_count(), and V3000conversion().
The documentation for this class was generated from the following files:
dlhandler.h
dlhandler_unix.cpp
dlhandler_win32.cpp