Mychem: property_wrapper.h File Reference
property_wrapper.h File Reference
Functions
double getMolWeight (const char *molecule)
double getExactMass (const char *molecule)
long long int getAtomCount (const char *molecule)
long long int getHeavyAtomCount (const char *molecule)
long long int getBondCount (const char *molecule)
long long int getRotableBondCount (const char *molecule)
long long int getTotalCharge (const char *molecule)
char * getFormula (const char *molecule)
long long int getAcceptors (const char *molecule)
long long int getDonors (const char *molecule)
double getPSA (const char *molecule)
double getMR (const char *molecule)
double getLogP (const char *molecule)
long long int is2D (const char *molecule)
long long int is3D (const char *molecule)
long long int isChiral (const char *molecule)
long long int getRingCount (const char *molecule)
Detailed Description
Wrapper for the Mychem property module.
This file is part of the Mychem software. It contains function declarations related to chemical property calculations.
Author
Jerome Pansanel jerom.nosp@m.e.pa.nosp@m.nsane.nosp@m.l@ip.nosp@m.hc.cn.nosp@m.rs.f.nosp@m.r
Aurelie De Luca aurel.nosp@m.iede.nosp@m.luca@.nosp@m.gmai.nosp@m.l.com
Bjoern Gruening bjoer.nosp@m.n@gr.nosp@m.uenin.nosp@m.gs.e.nosp@m.u
Function Documentation
double getMolWeight (const char * molecule)
Calculates the molecular weight of a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The molecular weight.
References LibHandler::isLoaded().
double getExactMass (const char * molecule)
Calculates the exact mass of a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The exact mass.
References LibHandler::isLoaded().
long long int getAtomCount (const char * molecule)
Returns the number of atoms in a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The number of atoms.
References LibHandler::isLoaded().
long long int getHeavyAtomCount (const char * molecule)
Returns the number of heavy atoms in a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The number of heavy atoms.
References LibHandler::isLoaded().
long long int getBondCount (const char * molecule)
Returns the number of bonds in a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The number of bonds.
References LibHandler::isLoaded().
long long int getRotableBondCount (const char * molecule)
Returns the number of rotable bonds in a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The number of rotable bonds.
References LibHandler::isLoaded().
long long int getTotalCharge (const char * molecule)
Returns the total charge of a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The total charge.
References LibHandler::isLoaded().
char* getFormula (const char * molecule)
Returns the formula of a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The formula.
References LibHandler::isLoaded().
long long int getAcceptors (const char * molecule)
Returns the number of hydrogen bond acceptors.
Parameters
molecule The molecule used for the calculation.
Returns
The number of hydrogen bond acceptors.
References LibHandler::isLoaded().
long long int getDonors (const char * molecule)
Returns the number of hydrogen bond donors.
Parameters
molecule The molecule used for the calculation.
Returns
The number of hydrogen bond donors.
References LibHandler::isLoaded().
double getPSA (const char * molecule)
Predicts the TPSA (Topological Polar Surface Area) of a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The topological polar surface area.
References LibHandler::isLoaded().
double getMR (const char * molecule)
Predicts the MR (Molar Refractivity) of a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The molar refractivity.
References LibHandler::isLoaded().
double getLogP (const char * molecule)
Predicts the LogP of a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The LogP.
References LibHandler::isLoaded().
long long int is2D (const char * molecule)
Checks if a molecule has 2D coordinates.
Parameters
molecule The molecule used for the calculation.
Returns
1 if the molecule has 2D coordinates.
References LibHandler::isLoaded().
long long int is3D (const char * molecule)
Checks if a molecule has 3D coordinates.
Parameters
molecule The molecule used for the calculation.
Returns
1 if the molecule has 3D coordinates.
References LibHandler::isLoaded().
long long int isChiral (const char * molecule)
Checks if a molecule is chiral.
Parameters
molecule The molecule used for the calculation.
Returns
1 if the molecule is chiral.
References LibHandler::isLoaded().
long long int getRingCount (const char * molecule)
Returns the number of rings in a molecule.
Parameters
molecule The molecule used for the calculation.
Returns
The number of rings (SSSR).
References LibHandler::isLoaded().