Mychem: serialization.cpp File Reference
serialization.cpp File Reference
#include <mychem/serialization.h>
#include <openbabel/stereo/stereo.h>
#include <openbabel/stereo/tetrahedral.h>
#include <openbabel/stereo/cistrans.h>
#include <openbabel/stereo/squareplanar.h>
Functions
char * serializeOBMol (OBMol &mol)
bool unserializeOBMol (OBBase *pOb, const char *serializedInput, bool stereoEnabled)
Detailed Description
OBMol Serialization Methods.
This file is part of the Mychem software. It contains functions related to the serialization of OBMol objects.
Author
Jerome Pansanel jerom.nosp@m.e.pa.nosp@m.nsane.nosp@m.l@ip.nosp@m.hc.cn.nosp@m.rs.f.nosp@m.r
Function Documentation
char* serializeOBMol (OBMol & mol)
References _ATOM::aromatic, _BOND::aromatic, _ATOM::atomicnum, _BOND::beginidx, _BOND::endidx, _ATOM::formalcharge, _ATOM::hybridization, _ATOM::idx, _ATOM::isotope, _BOND::order, and _ATOM::spinmultiplicity.
Referenced by serializeMolecule().
bool unserializeOBMol (OBBase * pOb, const char * serializedInput, bool stereoEnabled)
References _ATOM::aromatic, _BOND::aromatic, _ATOM::atomicnum, _BOND::beginidx, _BOND::endidx, _ATOM::formalcharge, _ATOM::hybridization, _ATOM::idx, _ATOM::isotope, _BOND::order, and _ATOM::spinmultiplicity.
Referenced by match_substructure(), substructure_atom_ids(), and substructure_count().